In [ ]:
#Perfect Bansal

Task 4
Problem 1

In [1]:
#2*2 matrix
import numpy as np

empty_array = np.empty((2, 2))
print(empty_array)


[[5.02683033e-310 0.00000000e+000]
 [6.64131254e-310 6.64131200e-310]]


In [4]:
#array with size 4X2
import numpy as np
ones_array = np.ones((4, 2))
print(ones_array)


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [6]:
3.
import numpy as np
array = np.full((3, 3), 7)
print(array)


[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [9]:
#4.
import numpy as np
given = np.array([[1, 2], [3, 4]])
zeros = np.zeros_like(given)
print(zeros)


[[0 0]
 [0 0]]


In [10]:
#5.
import numpy as np
array = np.ones_like(given)
print(array)


[[1 1]
 [1 1]]


In [11]:
#6.
import numpy as np
new_list = [1, 2, 3, 4]
array = np.array(new_list)
print(array)


[1 2 3 4]


Problem 2

In [12]:
#1.
import numpy as np

array = np.arange(10, 50)
print(array)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [13]:
#2
import numpy as np
matrix = np.arange(9).reshape(3, 3)
print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
#3
import numpy as np
identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
#4
import numpy as np
random_arr = np.random.random(30)
mean = random_arr.mean()
print("Mean of the array:", mean)


Mean of the array: 0.38259534833528475


In [23]:
#5
import numpy as np
array = np.random.rand(100)
answer = array.reshape(10,10)
max = max(array)
min = min(array)
print(answer)
print(f"the maximum value is: {max}")
print(f"the minimum value is: {min}")



[[0.02851524 0.92097696 0.45494917 0.94424238 0.9412925  0.74461007
  0.80234552 0.99325993 0.35281497 0.79115284]
 [0.77842894 0.55084351 0.66136137 0.12682408 0.92200713 0.28696696
  0.19113337 0.60061596 0.04066249 0.53488421]
 [0.82792157 0.31824664 0.4084949  0.79927882 0.33555322 0.98093065
  0.42131054 0.1235187  0.40870991 0.17569395]
 [0.37301289 0.1500723  0.30844242 0.30966735 0.63583895 0.15305245
  0.93742683 0.83666403 0.62982152 0.71696216]
 [0.81505331 0.52999873 0.39764172 0.96190517 0.04704766 0.58417543
  0.25179107 0.27510833 0.81114176 0.23391387]
 [0.99831678 0.49005481 0.66751994 0.28065045 0.96189322 0.33407772
  0.40793186 0.29929259 0.55312548 0.55280063]
 [0.90094785 0.97673773 0.54617929 0.9253856  0.56010842 0.51370686
  0.63263371 0.64954185 0.31642106 0.8530868 ]
 [0.3147763  0.9056361  0.9836737  0.34018981 0.43708073 0.63148681
  0.7388108  0.74904138 0.27265157 0.66633666]
 [0.55178054 0.61749269 0.0226423  0.40482229 0.38857794 0.51158798
  0.90563272

In [24]:
#6
import numpy as np
arr = np.zeros(10)
arr[4] = 1
print(arr)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [19]:
#7
import numpy as np
array = np.array([1, 2, 0, 0, 4, 0])
reversed = array[::-1]
print(reversed)


[0 4 0 0 2 1]


In [20]:
#8
import numpy as np
array = np.ones((5, 5))
array[1:-1, 1:-1] = 0
print(array)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [25]:
#9
import numpy as np

checkerboard = np.zeros((8, 8))

for i in range(8):
    for j in range(8):
        if (i + j) % 2 == 0:
            checkerboard[i, j] = 1
        else:
            checkerboard[i, j] = 0

print(checkerboard)


[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


problem 3

In [26]:
#!
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

#Add
add = x + y
print("Addition of x and y:\n", add)

#Subtract
subtract = x - y
print("Subtraction of x and y:\n", subtract)

#Multiply
multiply = x * 2
print("Multiplication of x by 2:\n", multiply)

# square of each element
square= x ** 2
print("Square of each element of x:\n", square)

#dot product between:
# v and w
dot_vw = np.dot(v, w)
print("Dot product of v and w:", dot_vw)

# x and v
dot_xv = np.dot(x, v)
print("Dot product of x and v:\n", dot_xv)

# x and y
dot_xy = np.dot(x, y)
print("Dot product of x and y:\n", dot_xy)

#Concatenate x and y along rows and v and w along columns
xy_row = np.concatenate((x, y), axis=0)
print("Concatenation of x and y along rows:\n",xy_row)

vw_col = np.concatenate((v[:, np.newaxis], w[:, np.newaxis]), axis=1)
print("Concatenation of v and w along columns:\n", vw_col)


Addition of x and y:
 [[ 6  8]
 [10 13]]
Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]
Multiplication of x by 2:
 [[ 2  4]
 [ 6 10]]
Square of each element of x:
 [[ 1  4]
 [ 9 25]]
Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]
Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of v and w along columns:
 [[ 9 11]
 [10 12]]


Probmem 4

In [27]:
#1
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
inverse = np.linalg.inv(A)
mul = np.dot(A ,inverse)
print(mul)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [28]:
#2
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
product1 = np.dot(A,B)
product2 = np.dot(B,A)
comparison = product1 == product2
print(comparison)

[[False False]
 [False False]]


In [29]:
#3
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
product = np.dot(A,B)
transpose = np.transpose(product)
transpose1 = np.transpose(A)
transpose2 = np.transpose(B)
product1 = np.dot(transpose2,transpose1)
comparison = transpose == product1
print(comparison)

[[ True  True]
 [ True  True]]


In [30]:
#4
import numpy as np
A = np.array([[2, -3, 1],[1, -1, 2],[3, 1, -1]])
B = np.array([-1, -3, 9])
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print(f"the value of x y and z is: {X}")


the value of x y and z is: [ 2.  1. -2.]
